config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "rentals/:id", to: "pages#rentals", as: :rentals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # get "/listings", to: "listings#index"
  resources :listings do
    resources :bookings, only: [:create, :new]
  end
  resources :bookings, only: [:show, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :start_date, date: { before: :end_date }
  validates :end_date, date: { after: :start_date }
  validates :total_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/listing.rb
class Listing < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [ :title, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  # multisearchable against: [:title, :description]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  validates :title, presence: true
  validates :description, presence: true
  validates :rental_price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :listings, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address phone])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address phone])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @new_booking = Booking.new(booking_params)
    @listing = Listing.find(params[:listing_id].to_i)
    @listing.availability = true
    @new_booking.listing = @listing
    @new_booking.user_id = current_user.id
    @new_booking.total_price = (@new_booking.end_date - @new_booking.start_date) / 86_400 * @listing.rental_price

    if @new_booking.save
      @listing.save
      redirect_to booking_path(@new_booking)
    else
      render "listings/show", status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @listing = Listing.find(@booking.listing_id)
  end

  def destroy
    if @booking.destroy
      redirect_to bookings_path(@booking)
    else
      render :index
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :destroy, :edit, :update]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      @listings = Listing.search_by_title_and_description(params[:query])
    else
      @listings = Listing.where.not(user: current_user)
    end
  end

  def new
    @listing = Listing.new
  end

  def show
    @booking = Booking.find_by(listing_id: @listing.id)
    @new_booking = Booking.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.availability = true
    if @listing.save
      redirect_to @listing, notice: "Listing was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @listing.update(listing_params)
      redirect_to @listing, notice: "Listing was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @listing.destroy
    redirect_to dashboard_path, notice: "Listing was successfully destroyed."
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :rental_price, :availability, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @listings = Listing.where.not(user: current_user).first(4)
  end

  def dashboard
    @listings = Listing.where(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)
  end

  def rentals
    @listing = Listing.find(params[:id])
    @bookings = Booking.where(listing_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container col-lg-3 mt-3">
  <%= simple_form_for [@listing, @booking] do |f| %>
    <%= f.input :start_date, as: :date, html5: true %>
    <%= f.input :end_date, as: :date, html5: true %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="container col-lg-3 mt-3">
  <h1>Booking summary</h1>
  <div class="card-product d-flex align-items-center justify-content-between mb-2">
    <% if @listing.photos.any? %>
      <%= cl_image_tag @listing.photos.first.key, class: "card-img-top"%>
    <% else %>
      <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg" alt="Placeholder">
    <% end %>
    <div class="card-product-infos flex-fill ms-3">
      <h3 class="m-0"><%= @listing.title %></h3>
    </div>
  </div>
  <ul class="list-group">
    <li class="list-group-item"> Your pick up date is <strong><%= @booking.start_date.to_time.strftime('%B %e ')%></strong></li>
    <li class="list-group-item"> You must return the product by <strong><%= @booking.end_date.to_time.strftime('%B %e  ') %></strong></li>
    <li class="list-group-item">The amount owing is <strong>$<%= number_with_precision(@booking.total_price, precision: 2) %></strong></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gaming Zone</title>
    <title>Gaming Zone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<div class="container col-lg-6 mt-3">
  <h1 class="text-center">Create a new listing</h1>
  <%= simple_form_for @listing do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :rental_price, label: "Rental rate per day", as: :decimal %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/listings/edit.html.erb
<%= render "form" %>

app/views/listings/index.html.erb
<div class="container my-3">
  <div class="container col-8 my-5">
    <form novalidate="novalidate" class="simple_form search" action="/listings" accept-charset="UTF-8" method="get">
      <div class="search-form-control form-group">
        <input class="form-control string required" type="text" name="query" id="search_query" placeholder="Find your favourite console" value="<%= params[:query] %>"/>
        <button name="button" type="submit" class="btn btn-success"><i class="fas fa-search"></i> Search</button>
      </div>
    </form>
  </div>
  <div class="row gy-4">
    <% @listings.each do |listing| %>
      <div class="col-3">
        <div class="card">
          <% if listing.photos.any? %>
            <%= cl_image_tag listing.photos.first.key, class: "card-img-top" %>
          <% else %>
            <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= listing.title %></h5>
            <div class="d-flex justify-content-between align-items-center">
              <%= link_to "More info", listing_path(listing), class: "btn btn-primary" %>
              <h5>$<%= number_with_precision(listing.rental_price , precision: 2) %>/day</h5>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/listings/listing.html.erb
<h1> The best consoles you will ever see </h1>

<ul>
  <% @listings.each do |listing| %>
    <li><%= listing.title %></li>
    <% end %>
</ul>

app/views/listings/new.html.erb
<div class="container col-lg-3 mt-3">
  <h1>Create a new listing</h1>
  <%= simple_form_for @listing do |f| %>
    <%= f.input :title %>
    <%= f.input :description, as: :text %>
    <%= f.input :rental_price, label: "Rental rate per day", as: :decimal %>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.submit %>
  <% end %>
</div>

app/views/listings/show.html.erb
<div class="container col-lg-4 mt-3">
  <h1><%= @listing.title %></h1>
  <div class="row">
    <div id="carouselExampleControls" class="carousel slide col-8" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% if @listing.photos.any? %>
          <% @listing.photos.each do |photo| %>
            <div class="carousel-item active" style="border: 5px solid white">
              <%= cl_image_tag photo.key, class: "d-block w-100" %>
            </div>
          <% end %>
        <% else %>
          <div class="carousel-item active">
            <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg" class="w-100" style="border: 5px solid white">
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div class="col-4">
      <p class="fs-3 fw-semibold mb-0">$<%= number_with_precision(@listing.rental_price, precision: 2) %>/day</p>
      <% if @listing.user == current_user %>
        <%= link_to "Edit", edit_listing_path(@listing), class: "btn btn-primary"  %>
        <%= link_to "Delete", listing_path(@listing), class: "btn btn-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <% else %>
        <%= simple_form_for [@listing, @new_booking],  data: { turbo: false } do |f| %>
          <%= f.input :start_date, as: :date, html5: true %>
          <%= f.input :end_date, as: :date, html5: true %>
          <%= f.button :submit, class: "btn btn-primary"%>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="mt-3">
    <p><%= @listing.description %></p>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container col-lg-6 mt-3">
  <h1>Dashboard</h1>
  <h2>My Listings</h2>
  <ul class="list-group">
    <% @listings.each do |listing| %>
    <li class="list-group-item mb-2">
      <div class="d-flex align-items-center justify-content-between">
        <% if listing.photos.any? %>
          <%= cl_image_tag listing.photos.first.key, class: "card-img-top", style: "width: 100px" %>
        <% else %>
          <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg" alt="Placeholder" style="width: 100px">
        <% end %>
        <div class="flex-fill ms-2">
          <h5><%= listing.title %></h5>
        </div>
        <div>
          <%= link_to rentals_path(listing), title: "Rentals", target: :_blank do %><i class="fa-solid fa-calendar-days"></i><% end %>
          <%= link_to listing_path(listing), title: "View", target: :_blank do %><i class="fa-solid fa-eye"></i><% end %>
          <%= link_to edit_listing_path(listing), title: "Edit" do %><i class="fa-solid fa-pen-to-square"></i><% end %>
          <%= link_to listing_path(listing), title: "Delete", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %><i class="fa-sharp fa-solid fa-trash"></i><% end %>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
  <h2 class="mt-3">My Bookings</h2>
  <ul class="list-group">
    <% @bookings.each do |booking| %>
    <li class="list-group-item mb-2"><%= Listing.find(booking.listing_id).title %> (Returned by: <%= booking.end_date.strftime('%B %e ') %>)</li>
  <% end %>
  </ul>
</div>

app/views/pages/home.html.erb
<div class="banner text-center">
  <div class="text-white pt-5">
    <h1>Gaming Zone🎮</h1>
    <h5>Get gaming today</h5>
    <div class="container">
      <div class="center">
        <%= link_to "Game away", listings_path(@listing), class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>
<div class="container my-3">
  <h2>Lastest Listings</h2>
  <div class="row gy-4">
    <% @listings.each do |listing| %>
      <div class="col-3">
        <div class="card">
          <% if listing.photos.any? %>
            <%= cl_image_tag listing.photos.first.key, class: "card-img-top" %>
          <% else %>
            <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg" alt="Placeholder">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= listing.title %></h5>
            <% if false %>
            <%# if listing.availability %>
              <%# link_to "More info", listing_path(listing), class: "btn btn-primary" %>
            <% else %>
              <%# <p class="text-align-center" style="color: white; background: red">Currently unavailable.</p> %>
            <% end %>
              <%= link_to "More info", listing_path(listing), class: "btn btn-primary" %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= render "shared/footer" %>

app/views/pages/rentals.html.erb
<div class="container col-4 mt-3">
  <div class="card-product d-flex align-items-center justify-content-between mb-4">
    <% if @listing.photos.any? %>
      <%= cl_image_tag @listing.photos.first.key, class: "card-img-top"%>
    <% else %>
      <img src="https://res.cloudinary.com/dq9hvwxj8/image/upload/v1669199190/hhth1iyyoguqnzs7hg9e.jpg" alt="Placeholder">
    <% end %>
    <div class="card-product-infos flex-fill ms-3">
      <h3 class="m-0"><%= @listing.title %></h3>
    </div>
  </div>
  <% if !@bookings.empty? %>
    <h3>Active rentals</h3>
    <ul class="list-group">
      <% @bookings.each do |booking| %>
        <li class="list-group-item mb-2" >
          <% if User.find_by(id: booking.user_id).first_name.nil? %>
            <strong><%= User.find_by(id: booking.user_id).email %></strong>
          <% else %>
            <strong><%= User.find_by(id: booking.user_id).first_name %> <%= User.find_by(id: booking.user_id).last_name %></strong>
          <% end %>
          has made a booking from
          <strong><%= booking.start_date.strftime('%B %e ') %></strong>
          to
          <strong><%= booking.end_date.strftime('%B %e ') %></strong>
        </li>
      <% end %>
    </ul>
  <% else %>
    <h3>No active bookings :(</h3>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <%# <a href="#"><i class="fab fa-github"></i></a> %>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <%# <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a> %>
  </div>
  <div class="footer-copyright">
    Check our socials!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-sm.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
            <%= link_to "Browse", listings_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "avatar.webp", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add New Listing", new_listing_path, class: "nav-link" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>